spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${LOCAL.DATABASE.URL}
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${LOCAL.GOOGLE.CLIENT_ID}
            clientSecret: ${LOCAL.GOOGLE.CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email, profile
          github:
            clientId: ${LOCAL.GITHUB.CLIENT_ID}
            clientSecret: ${LOCAL.GITHUB.CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: user:email,read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  mail:
    host: smtp.gmail.com
    username: ${LOCAL_SMTP_EMAIL_USERNAME}
    password: ${LOCAL_SMTP_EMAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
server:
  port: 8081