spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authModule
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/accounts/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: false #Por enquanto valor padrão é true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
