spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authModule
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/accounts/**
            - Path=/api/v1/recovery/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - https://www.taskfreela.com
              - http://localhost:3000
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
