spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authModule
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/