server:
  port: 8083
spring:
  application:
    name: project-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${LOCAL.DATABASE.URL}
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
openapi:
  service:
    title: project-service doc
    version: 1.0.0
    url: http://localhost:9090

springdoc:
  api-docs:
    path: /project-service/v3/api-docs
  swagger-ui:
    path: /project-service/swagger-ui.html
tech:
  engix:
    jwtSecret: ${MY_SECRET_JWT}
    service:
      url: ${SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: prometheus