spring:
  application:
    name: eureka-server
eureka:
  instance:
    prefer-ip-address: true
    host-name: eureka-server
    lease-renewal-interval-in-seconds: 10

  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761