server:
  port: 8082
spring:
  application:
    name: tasks-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ${MG_DATABASE_USERNAME}
      password: ${MG_DATABASE_PASSWORD}
      authentication-database: admin
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

openapi:
  service:
    title: tasks-service doc
    version: 1.0.0
    url: http://localhost:9090

springdoc:
  api-docs:
    path: /tasks-service/v3/api-docs
  swagger-ui:
    path: /tasks-service/swagger-ui.html

tech:
  engix:
    jwtSecret: ${MY_SECRET_JWT}
    service:
      url: ${SERVICE_URL}