spring:
  data:
    mongodb:
      url: ${LOCAL.DATABASE.URL}
      username: ${LOCAL.DATABASE.USERNAME}
      password: ${LOCAL.DATABASE.PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
server:
  port: 8082